global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'bot_bg'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['bot_bg:8000']
