global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'bot_bg'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['bot_bg:8000']

  - job_name: 'bot_sr'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['bot_sr:8000']

  - job_name: 'node_exporter_host'
    static_configs:
      - targets: [ 'host.docker.internal:9100' ]
    params:
      collect[]:
        - cpu
        - meminfo
        - filesystem

  - job_name: 'notifier'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['notifier:8000']

#  - job_name: 'prometheus'
#    static_configs:
#      - targets: ['localhost:9090']