"""Initial

Revision ID: 0d252a5f4028
Revises:
Create Date: 2025-03-04 22:51:22.848707

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0d252a5f4028'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'exercises',
        sa.Column('exercise_id', sa.Integer(), nullable=False),
        sa.Column('exercise_type', sa.String(), nullable=False),
        sa.Column('language_level', sa.String(), nullable=False),
        sa.Column('topic', sa.String(), nullable=False),
        sa.Column('exercise_text', sa.Text(), nullable=False),
        sa.Column(
            'data', postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint('exercise_id'),
    )
    op.create_index(
        op.f('ix_exercises_exercise_id'),
        'exercises',
        ['exercise_id'],
        unique=False,
    )
    op.create_table(
        'cached_answers',
        sa.Column('answer_id', sa.Integer(), nullable=False),
        sa.Column('exercise_id', sa.Integer(), nullable=False),
        sa.Column(
            'answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column('answer_text', sa.Text(), nullable=False),
        sa.Column('is_correct', sa.Boolean(), nullable=False),
        sa.Column('feedback', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_by', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['exercise_id'], ['exercises.exercise_id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('answer_id'),
    )
    op.create_index(
        op.f('ix_cached_answers_answer_id'),
        'cached_answers',
        ['answer_id'],
        unique=False,
    )
    op.create_table(
        'exercise_attempts',
        sa.Column('attempt_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('exercise_id', sa.Integer(), nullable=False),
        sa.Column(
            'answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column('is_correct', sa.Boolean(), nullable=False),
        sa.Column('feedback', sa.String(), nullable=True),
        sa.Column('cached_answer_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['cached_answer_id'],
            ['cached_answers.answer_id'],
            ondelete='SET NULL',
        ),
        sa.ForeignKeyConstraint(
            ['exercise_id'], ['exercises.exercise_id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('attempt_id'),
    )
    op.create_index(
        op.f('ix_exercise_attempts_attempt_id'),
        'exercise_attempts',
        ['attempt_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_exercise_attempts_attempt_id'), table_name='exercise_attempts'
    )
    op.drop_table('exercise_attempts')
    op.drop_index(
        op.f('ix_cached_answers_answer_id'), table_name='cached_answers'
    )
    op.drop_table('cached_answers')
    op.drop_index(op.f('ix_exercises_exercise_id'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
