"""user_status

Revision ID: 1419c0fd5833
Revises: 7c2c98f6df06
Create Date: 2025-06-07 23:32:43.206187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1419c0fd5833'
down_revision: Union[str, None] = '7c2c98f6df06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_bot_profiles', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=50), server_default='free', nullable=False))
    op.add_column('users', sa.Column('status_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('status_source', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('custom_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'custom_settings')
    op.drop_column('users', 'status_source')
    op.drop_column('users', 'status_expires_at')
    op.drop_column('users', 'status')
    op.drop_column('user_bot_profiles', 'settings')
    # ### end Alembic commands ###
