"""fix:exercise_attempts exercise_answerS_id -> answer_id

Revision ID: 230a7f896121
Revises: cd9c2bc807a9
Create Date: 2025-04-01 14:45:13.679212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230a7f896121'
down_revision: Union[str, None] = 'cd9c2bc807a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_attempts', sa.Column('answer_id', sa.Integer(), nullable=True))
    op.drop_constraint('exercise_attempts_exercise_answers_id_fkey', 'exercise_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'exercise_attempts', 'exercise_answers', ['answer_id'], ['answer_id'], ondelete='SET NULL')
    op.drop_column('exercise_attempts', 'exercise_answers_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_attempts', sa.Column('exercise_answers_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'exercise_attempts', type_='foreignkey')
    op.create_foreign_key('exercise_attempts_exercise_answers_id_fkey', 'exercise_attempts', 'exercise_answers', ['exercise_answers_id'], ['answer_id'], ondelete='SET NULL')
    op.drop_column('exercise_attempts', 'answer_id')
    # ### end Alembic commands ###
