"""profile extend for notifier

Revision ID: 381d12432191
Revises: b9e3695ff304
Create Date: 2025-05-12 14:30:53.569206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381d12432191'
down_revision: Union[str, None] = 'b9e3695ff304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_bot_profiles', sa.Column('wants_session_reminders', sa.Boolean(), nullable=True))
    op.add_column('user_bot_profiles', sa.Column('last_long_break_reminder_type_sent', sa.String(), nullable=True))
    op.add_column('user_bot_profiles', sa.Column('last_long_break_reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_bot_profiles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_bot_profiles', 'created_at')
    op.drop_column('user_bot_profiles', 'last_long_break_reminder_sent_at')
    op.drop_column('user_bot_profiles', 'last_long_break_reminder_type_sent')
    op.drop_column('user_bot_profiles', 'wants_session_reminders')
    # ### end Alembic commands ###
