"""Initial migration

Revision ID: 422c6cb186e6
Revises:
Create Date: 2025-03-30 00:47:06.088875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '422c6cb186e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('exercise_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_type', sa.String(), nullable=False),
    sa.Column('exercise_language', sa.String(), nullable=False),
    sa.Column('language_level', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('exercise_text', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_index(op.f('ix_exercises_exercise_id'), 'exercises', ['exercise_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_language', sa.String(), nullable=True),
    sa.Column('target_language', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('language_level', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('exercise_answers',
    sa.Column('answer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('feedback_language', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.exercise_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_index(op.f('ix_exercise_answers_answer_id'), 'exercise_answers', ['answer_id'], unique=False)
    op.create_table('exercise_attempts',
    sa.Column('attempt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('exercise_answers_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_answers_id'], ['exercise_answers.answer_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.exercise_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_index(op.f('ix_exercise_attempts_attempt_id'), 'exercise_attempts', ['attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_attempts_attempt_id'), table_name='exercise_attempts')
    op.drop_table('exercise_attempts')
    op.drop_index(op.f('ix_exercise_answers_answer_id'), table_name='exercise_answers')
    op.drop_table('exercise_answers')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_exercises_exercise_id'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
