"""initial migration

Revision ID: 6951b13fb891
Revises:
Create Date: 2025-03-14 19:02:22.064709

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '6951b13fb891'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
