"""add_new_enum_exercise_status

Revision ID: 7c2c98f6df06
Revises: 86c7163721fc
Create Date: 2025-06-06 14:55:31.736256

"""
from typing import Sequence, Union

from alembic import op

from app.core.configs.enums import ExerciseStatus

# revision identifiers, used by Alembic.
revision: str = '7c2c98f6df06'
down_revision: Union[str, None] = '86c7163721fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


enum_name = 'exercise_status_enum'
new_statuses = [
    ExerciseStatus.PENDING_ADMIN_REVIEW.value,
]

def upgrade() -> None:
    """Upgrade schema."""
    for status_value in new_statuses:
        op.execute(f"ALTER TYPE {enum_name} ADD VALUE IF NOT EXISTS '{status_value}'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
