"""new fields for user_progress

Revision ID: 7e4e7bd50bdf
Revises: 230a7f896121
Create Date: 2025-04-02 22:49:13.435011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e4e7bd50bdf'
down_revision: Union[str, None] = '230a7f896121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('exercises_get_in_session', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('exercises_get_in_set', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('errors_count_in_set', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_exercise_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('is_waiting_next_session', sa.Boolean(), nullable=True))

    # Populate existing rows with default values
    op.execute("UPDATE users SET exercises_get_in_session = 0")
    op.execute("UPDATE users SET exercises_get_in_set = 0")
    op.execute("UPDATE users SET errors_count_in_set = 0")
    op.execute("UPDATE users SET is_waiting_next_session = false")

    # Now make the columns NOT NULL
    op.alter_column('users', 'exercises_get_in_session', nullable=False, server_default='0')
    op.alter_column('users', 'exercises_get_in_set', nullable=False, server_default='0')
    op.alter_column('users', 'errors_count_in_set', nullable=False, server_default='0')
    op.alter_column('users', 'is_waiting_next_session', nullable=False, server_default='false')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_waiting_next_session')
    op.drop_column('users', 'last_exercise_at')
    op.drop_column('users', 'errors_count_in_set')
    op.drop_column('users', 'exercises_get_in_set')
    op.drop_column('users', 'exercises_get_in_session')
    # ### end Alembic commands ###
