"""bot_id enum -> str

Revision ID: 8093d4b4ceb3
Revises: 1b2c3d4e5f6a
Create Date: 2025-06-25 12:10:32.514727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8093d4b4ceb3'
down_revision: Union[str, None] = '1b2c3d4e5f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'bot_id',
               existing_type=postgresql.ENUM('BG', 'Bulgarian', name='bot_id_enum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'bot_id',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('BG', 'Bulgarian', name='bot_id_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
