"""exercise_id index

Revision ID: 853581da4692
Revises: 6b35378d065b
Create Date: 2025-04-14 18:14:21.026094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '853581da4692'
down_revision: Union[str, None] = '6b35378d065b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_exercise_answers_exercise_id'), 'exercise_answers', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_attempts_exercise_id'), 'exercise_attempts', ['exercise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_attempts_exercise_id'), table_name='exercise_attempts')
    op.drop_index(op.f('ix_exercise_answers_exercise_id'), table_name='exercise_answers')
    # ### end Alembic commands ###
