"""add_status_to_weekly_report

Revision ID: 9e3ca364e1ee
Revises: e5e4f4b3c2d1
Create Date: 2025-06-19 16:11:02.911821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e3ca364e1ee'
down_revision: Union[str, None] = 'e5e4f4b3c2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_reports', sa.Column('status', sa.String(length=50), server_default='PENDING', nullable=False))
    op.create_index(op.f('ix_user_reports_status'), 'user_reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_reports_status'), table_name='user_reports')
    op.drop_column('user_reports', 'status')
    # ### end Alembic commands ###
