"""change_bot_id_to_string

Revision ID: a9c183771320
Revises: 384e45ddaca5
Create Date: 2025-06-05 16:57:56.957228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9c183771320'
down_revision: Union[str, None] = '384e45ddaca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_bot_profiles', 'bot_id',
               existing_type=postgresql.ENUM('BG', 'Bulgarian', name='bot_id_enum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


enum_name = 'bot_id_enum'
table_name = 'user_bot_profiles'
column_name = 'bot_id'

def downgrade():
    op.execute(
        f"ALTER TABLE {table_name} ALTER COLUMN {column_name} TYPE {enum_name} USING {column_name}::{enum_name};"
    )