"""add_date_last_report_user_profile

Revision ID: f1bc5bd4324a
Revises: 5f8c6a2e4b3d
Create Date: 2025-06-17 13:29:49.926511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1bc5bd4324a'
down_revision: Union[str, None] = '5f8c6a2e4b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_bot_profiles', sa.Column('last_report_generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_bot_profiles', 'last_report_generated_at')
    # ### end Alembic commands ###
