"""Initial migration

Revision ID: fd4902091779
Revises:
Create Date: 2025-03-27 14:06:57.502477

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'fd4902091779'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
