"""add_user_bot_profile_rating

Revision ID: ff5d5d529cd2
Revises: 317bab7a928c
Create Date: 2025-06-03 18:36:12.346793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5d5d529cd2'
down_revision: Union[str, None] = '317bab7a928c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_bot_profiles', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('user_bot_profiles', sa.Column('rating_last_calculated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_bot_profiles', 'rating_last_calculated_at')
    op.drop_column('user_bot_profiles', 'rating')
    # ### end Alembic commands ###
