"""exercise_status_enum

Revision ID: ffa998e24036
Revises: 747b459b6d09
Create Date: 2025-05-30 19:55:36.027157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.core.enums import ExerciseStatus

# revision identifiers, used by Alembic.
revision: str = 'ffa998e24036'
down_revision: Union[str, None] = '747b459b6d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    exercise_status_enum_type = postgresql.ENUM(
        *[status.value for status in ExerciseStatus],
        name='exercise_status_enum'
    )
    exercise_status_enum_type.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'exercises',
        sa.Column(
            'status',
            exercise_status_enum_type,
            server_default=ExerciseStatus.PUBLISHED.value,
            nullable=False
        )
    )
    op.create_index(op.f('ix_exercises_status'), 'exercises', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_status'), table_name='exercises')
    op.drop_column('exercises', 'status')
    exercise_status_enum_type = postgresql.ENUM(name='exercise_status_enum')
    exercise_status_enum_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
