BASE_SYSTEM_PROMPT_FOR_GENERATION = (
    'You are a language learning expert creating exercises '
    'for a {user_language}-speaking learner '
    'of the {exercise_language} language at the {language_level} '
    'level, focusing on the topic: {topic}.\n'
    'Follow the instructions carefully to generate a high-quality exercise.\n'
    'Ensure all generated text, including correct answers '
    'and incorrect options, uses *only* characters '
    'from the {exercise_language} alphabet. Do not use visually similar '
    'characters from other alphabets '
    "(e.g., Latin 'o' instead of Cyrillic 'о' in a Cyrillic language "
    'exercise, or vice-versa if generating for Latin-based languages).\n'
    '\n{specific_exercise_generation_instructions}\n\n'
    'Output format instructions: {format_instructions}'
)

FILL_IN_THE_BLANK_GENERATION_INSTRUCTIONS = (
    "Your task is to generate a 'fill-in-the-blank' exercise.\n"
    'Follow these steps using a Chain of Thought approach:\n'
    '1.  **Sentence Conception:** Create a grammatically correct and natural '
    'sentence in {exercise_language} that is appropriate for the '
    '{language_level} and {topic}. The sentence should be clear '
    'and unambiguous. '
    'The sentence should be interesting and not overly simplistic.\n'
    '2.  **Blank Selection:** Identify 1 or 2 key words in the sentence '
    "to replace with blanks (represented by '___'). These words should be "
    'important for understanding, represent a common grammatical point, '
    'or be relevant vocabulary for the topic and level. '
    'The words chosen for blanks should ideally not be easily guessable '
    'without understanding the context or grammar.\n'
    '3.  **Correct Words:** List the exact word(s) that correctly fill '
    'the blank(s), in order. These are the `correct_words`.\n'
    '4.  **Incorrect Options (Distractors) Generation:** For each blank, '
    'generate 1-2 incorrect but plausible-sounding options. These options, '
    'when inserted into the blank, *must* result in a sentence that is:\n'
    'a.  Grammatically incorrect (e.g., wrong case, tense, agreement, '
    'spelling within {exercise_language} standards).\n'
    'b.  Semantically absurd or nonsensical in the context of the sentence.\n'
    'c.  Clearly and unambiguously wrong for a native speaker or an advanced '
    'learner focusing on correctness.\n'
    '    *Crucially, an incorrect option should NOT simply change the '
    'meaning of the sentence to another valid, sensible sentence in '
    '{exercise_language}. The goal is to test specific knowledge, not to '
    'allow for alternative correct sentences via distractors.*\n'
    '    These incorrect options will form the `incorrect_options` list. '
    'Ensure these options also only use {exercise_language} alphabet '
    'characters.\n'
    '5.  **Self-Critique and Refinement (Very Important):\n'
    '    -   Review the generated `sentence_with_blanks`, the '
    '`correct_words`, and the `incorrect_options`.\n'
    '    -   **Test with Incorrect Options:** Imagine filling the blanks '
    'with each of the `incorrect_options`. '
    '        If any incorrect option results in a sentence that is still '
    "grammatically correct and makes reasonable sense (even if it's a "
    'different meaning than intended with the correct words), then the '
    'exercise is not suitable. '
    '        In this case, you *must* go back to Step 1 (new sentence) '
    'or Step 2 (different blanks/words) and try again. '
    '        The exercise fails if incorrect options lead to valid '
    'alternative sentences rather than clear errors or absurdity.\n'
    '    -   **Alphabet Check:** Double-check that all words (correct and '
    'incorrect options) use *only* characters from the {exercise_language} '
    'alphabet. '
    '        For example, if {exercise_language} is Russian or Bulgarian, '
    "do not use Latin 'a', 'o', 'c', 'p', 'x', etc., instead "
    "of Cyrillic 'а', 'о', 'с', 'р', 'х'. "
    "        If {exercise_language} is English, do not use Cyrillic 'а' "
    "for 'a'.\n"
    '6.  **Final Output:** Provide the `sentence_with_blanks`, '
    '`correct_words` (list of strings for the blanks),'
    ' and `incorrect_options` '
    '(list of strings that are definitively wrong distractors).'
)

CHOOSE_SENTENCE_GENERATION_INSTRUCTIONS = (
    "Your task is to generate a 'choose the correct sentence' exercise.\n"
    'Follow these steps using a Chain of Thought approach:\n'
    '1.  **Correct Sentence Conception:** Create a grammatically correct, '
    'natural, and unambiguous sentence in {exercise_language}. '
    '    This sentence should be appropriate for the {language_level} '
    'and {topic}. '
    '    It should be interesting and not overly simplistic. This will be '
    'the `correct_sentence`.\n'
    '2.  **Incorrect Sentences (Distractors) Generation:** Create 2 '
    'distinct incorrect sentences. '
    '    Each incorrect sentence must:\n'
    '    a.  Be very similar in structure and vocabulary to the '
    '`correct_sentence`.\n'
    '    b.  Contain a single, clear, and common grammatical error '
    'relevant to the {language_level} '
    '        (e.g., wrong verb tense, incorrect noun case, wrong preposition, '
    'incorrect word order if it leads to a clear error, '
    "        subject-verb agreement error, incorrect article usage if it's a "
    'definitive error, common spelling mistake based on {exercise_language} '
    'rules).\n'
    '    c.  The error should make the sentence unambiguously incorrect '
    'for a native speaker or an advanced learner focusing on correctness.\n'
    '    d.  An incorrect sentence should NOT be just a semantically '
    'different but still grammatically correct sentence. '
    '        It must contain a grammatical or structural flaw.\n'
    '    e.  Ensure these incorrect sentences also only use '
    '{exercise_language} alphabet characters.\n'
    '    These will be part of the `options` list.\n'
    '3.  **Self-Critique and Refinement (Very Important):\n'
    '    -   Review the `correct_sentence` and the two '
    '`incorrect_sentences`.\n'
    '    -   **Plausibility of Incorrect Options:** Are the incorrect '
    'options plausible distractors? Do they target common errors?\n'
    '    -   **Clarity of Errors:** Is the error in each incorrect '
    'sentence clear and unambiguous? '
    '        Could an incorrect sentence be misinterpreted as correct or '
    'merely stylistically different?\n'
    '    -   **Uniqueness of Correct Sentence:** Is the `correct_sentence` '
    'clearly the *only* correct one among the three options? '
    "        If one of the 'incorrect' sentences is actually also correct "
    'or only very subtly awkward, the exercise is not suitable. '
    '        In this case, you *must* go back to Step 1 '
    '(new correct sentence) or Step 2 (new incorrect sentences with clearer '
    'errors) and try again.\n'
    '    -   **Alphabet Check:** Double-check that all sentences '
    '(correct and incorrect) use *only* characters from the '
    '{exercise_language} alphabet. '
    '        For example, if {exercise_language} is Russian or Bulgarian, do '
    "not use Latin 'a', 'o', 'c', 'p', 'x', etc., instead "
    "of Cyrillic 'а', 'о', 'с', 'р', 'х'.\n"
    '4.  **Final Output:** Provide the `correct_sentence` and '
    'a list of two `incorrect_sentences`.'
)

STORY_COMPREHENSION_GENERATION_INSTRUCTIONS = (
    "Your task is to generate a 'Story Comprehension' exercise.\n"
    'Follow these steps:\n'
    '\n'
    '1. **Story Generation:**\n'
    '   - Create a short, coherent story (3–5 sentences) in '
    '{exercise_language}.\n'
    '   - The story should be appropriate for the {language_level} '
    'and the topic: {topic}.\n'
    '   - Use natural, grammatically correct language suitable for '
    'a learner.\n'
    '   - Ensure the story is grammatically correct and uses natural'
    ' language.\n'
    '\n'
    '2. **Statements Generation:**\n'
    '   - Based on the story, generate three distinct statements:\n'
    '     a. `correct_statement`: a statement that accurately reflects '
    "the story's content.\n"
    '     b. `incorrect_statements` (2 items): false statements that '
    'are **plausible**, not obviously wrong.\n'
    '        - Use realistic alterations (e.g., change a character, '
    'time, place, quantity, or action).\n'
    '        - Reuse meaningful words from the story to make incorrect '
    'statements sound believable.\n'
    '        - Avoid statements that are clearly irrelevant, absurd, '
    'or grammatically incorrect.\n'
    '        - Do not create incorrect statements by simply negating '
    'the correct one.\n'
    '\n'
    '3. **Common Patterns for Incorrect Statements:**\n'
    '   - Switch the order of events\n'
    '   - Change details (e.g., number of people, colors, size)\n'
    '   - Replace subjects or objects with others mentioned in the story\n'
    '   - Introduce false but reasonable motivations or consequences\n'
    '\n'
    "The goal is to challenge the learner's attention to detail and memory, "
    'not to trick them with absurdities.'
)
