from datetime import timedelta

from app.core.enums import LanguageLevel

EXERCISE_FILL_IN_THE_BLANK_BLANKS = '___'
EXERCISE_FILL_IN_THE_BLANK_TASK = 'Заполни пробелы в предложении'

MIN_EXERCISE_COUNT_TO_GENERATE_NEW = 5

DEFAULT_LANGUAGE_LEVEL = LanguageLevel.A2
DEFAULT_USER_LEVEL = 'ru'
DEFAULT_TARGET_LANGUAGE = 'bg'

DEFAULT_BOT_MESSAGE_LANGUAGE = 'bg'
EXERCISES_IN_SET = 2
EXERCISES_IN_SESSION = EXERCISES_IN_SET * 3
DELTA_BETWEEN_SESSIONS = timedelta(seconds=3 * 60 * 60)
