from datetime import timedelta

from app.core.enums import LanguageLevel

EXERCISE_FILL_IN_THE_BLANK_BLANKS = '___'

MIN_EXERCISE_COUNT_TO_GENERATE_NEW = 5

DEFAULT_LANGUAGE_LEVEL = LanguageLevel.A2
DEFAULT_USER_LANGUAGE = 'ru'
DEFAULT_TARGET_LANGUAGE = 'bg'

DEFAULT_BOT_MESSAGE_LANGUAGE = 'bg'
EXERCISES_IN_SET = 5
SETS_IN_SESSION = 3
EXERCISES_IN_SESSION = EXERCISES_IN_SET * SETS_IN_SESSION
DELTA_BETWEEN_SESSIONS = timedelta(seconds=3 * 60 * 60)
RENEWING_SET_PERIOD = timedelta(
    seconds=int(DELTA_BETWEEN_SESSIONS.total_seconds() // SETS_IN_SESSION)
)
